### PR TITLE
Montery using OpenCore

### PR DESCRIPTION
**Pull request by Tresillo2017**
Update using OpenCore

### CODE REVIEW

**Comment by Tresillo2017** [comment]
Pls update the readme and add this since if you use this on a laptop you need to create another smbios for every laptop

https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#platforminfo

You CANT use the given in the config.plist since is already used with my account and If you don't change it I can have access to you hackintosh

**Comment by fidele007** [comment]
README.md updated. Thank you for your contribution :)

**Comment by Tresillo2017** [comment]
You are welcome, I will try to fix touchpad as soon as possible and I will
see if there's any workaround for HDMI output, btw I need to fix sleep and
fun keys

**Comment by Tresillo2017** [comment]
Hdmi is working fine

**Pull request merged**
